language: node_js
node_js:
  - "8"
  - "10"
  - "stable"
git:
  depth: 5
cache:
  directories:
  - "$HOME/.npm"
install:
  - npm i -g npm@6.9.0
  - npm ci
script:
  - npm test
  - npm run build-lib
  - npm run build-demo
