language: node_js
node_js:
  - "10"
  - "stable"
git:
  depth: 5
cache:
  directories:
  - "$HOME/.npm"
install:
  - npm i -g npm@6.14.5
  - npm ci
script:
  - npm test
  - npm run build-lib
  - npm run build-demo
